draw_set_color(c_white)
draw_text(10, 10, display_write_specs(display.app_surface))
draw_text(10, 30, display_write_specs(display.gui))
draw_text(10, 50, display_write_specs(display.screen))
draw_text(10, 70, display_write_specs(display.view))
draw_text(10, 90, display_write_specs(display.window))
draw_set_color(-1)